### PR TITLE
We should not be sanitizing the actual returned value at any time - sant...

### PR DESCRIPTION
**Pull request by sparkeleven**
...ization is for display purposes only.

Removed the sanitization of returned values inside DataGrid->getCellValue. Any santization required should be applied AFTER the actual value is returned rather than destroying data.

### CODE REVIEW

**Comment by zofe** [comment]
I can't  accept this pull request:

- by default it's ok that each column is sanitized, I hope that this is a common point of view.
- if you need to manage by yourself the way  of the value is sanitized you can:   
use a closure, column filters, blade syntax  accessing  $row->field.

About column filters you can see a demo here:
http://www.rapyd.com/rapyd-demo/filter
On the field "body"  there are some has some filters:
`$grid->add('body|strip_tags|substr[0,20]','Body');`  
where we can simply manage custom output in a short sintax using php functions.

**Comment by sparkeleven** [comment]
The issue here is that when the column is sanitized, it only takes the first 30 chars as per: str_limit(nl2br(htmlspecialchars($string)), 30);

This effectively destroys meaningful data on columns that don't have filters. I don't understand why you would want that as default behaviour? Surely the opposite case applies for truncation of data where you would use such a function?

**Comment by sparkeleven** [comment]
My particular use case: Clicking on a row in a DataGrid should perform a definable actions (such as go to edit screen, do a AJAX partial page update).

In this case, I can't think of an easier way other than to store the row ID in the first column that I then hide using ->style('display:none;') then use that field in a JQuery click event to call the DataGrid "Modify" action with the row's ID or call a predefined AJAX callback.

If columns are truncated by default, then it destroys meaningful data in a 40 character UUID, ID field, by default. I think that is counter-intuitive.

**Comment by zofe** [comment]
str_limit  is not concerning "sanitization"  I agree with you about this,  and 30 is a small limit.
I think that good compromise is moving  this handcoded value in the a config,  setting it by default at 100 chars.
what you do think about that?

**Comment by sparkeleven** [comment]
Agreed thought I suggest a config Boolean to turn the feature off altogether as well

**Comment by sparkeleven** [comment]
I can code this for you and submit pr

**Comment by zofe** [comment]
I agree and I thank you,  another config value or convention (i.e. "0  means no trunc..")  will be fine

**Comment by sparkeleven** [comment]
Agreed - will use zero for no limit

**Comment by sparkeleven** [comment]
Closed.

**Pull request closed without merging**
