### PR TITLE
Change http response data size & modify query string

### PR DESCRIPTION
**Pull request by icedfish**
1. change  query string from "xxx%" to "%xxx%",  I think it more usefully in most case.
2. reduce http response size.

### CODE REVIEW

**Comment by icedfish** [comment]
@zofe  please review this change.

**Comment by zofe** [comment]
- "change return data size & modify query string" is not a good idea  because "fields"  are intended to be used for search purpose and not as "result fields",   
. plus:  remote() method can use different fields as values
. plus: eloquent has already a way to purge unneeded json-data on queries  (protected $hidden property)

-  about like '%' position: I think that  ajax is needed on "massive" dataset,  where in my opinion LIKE "xxx%" is better choice than "%xxx%".
However I admit that a config value or a parameter should be a good idea to switch from one to another.

**Comment by icedfish** [comment]
1.  I known the fields is for search not for result, so there should be somewhere to define which fields should be return. and in the particular situation for 'autocomplete' field type. the  fields for search is enough for result. Return all fields is simple but improper.

2. I change it to  %xx% is because my point is  just the opposite of yours.
it's an sample controller to show people the POWER of autocomplete, so convenience is the first priority.
if the user has massive data, it's surely to write his own endpoint.

However, I still think of this controller as a piece of sample code, It's ok if you don't want to change : )

**Comment by zofe** [comment]
since there is a "remote" method  it's possible to customize a custom server endpoint.
I think that I missed a wiki page.. but there is a demo about how to use it properly:
http://www.rapyd.com/rapyd-demo/advancedform

This is another sample that show how to store serialized (comma separated) tags, using custom where and custom resultset. in a "no relation" context.

    $form->add('tags',Tags', 'tags')->remote('tagname', 'tagname', route('ajax.curriculum.tags'));
    ...
    public function getTagsAutocomplete()
    {
        return CurriculumTag::where("tagname","like","%{Input::get("q")}%")->take(10)->get(['tagname']);
    }

**Pull request closed without merging**
