### PR TITLE
Add HasMany support for DataForm

### PR DESCRIPTION
**Pull request by msabev**
When using the grid currently it's not possible to use an object with a hasMany relation which for me was a big miss.

### CODE REVIEW

**Comment by zofe** [comment]
can you explain a little bit better or refer to an opened issue?
thanks

**Comment by tacone** [comment]
A similar issue has been posted some day ago by another user: https://github.com/zofe/rapyd-laravel/issues/283

**Comment by msabev** [comment]
I am sorry, this is my first time as a contributor. My colleagues and I started using the filter and the grid for an internal project. But in some cases we got some objects with children which have a hasMany relation to another sub-objects and we needed to display them inside the grid. Before this fix we got the following exception: `The field hosted_proj is a Illuminate\Database\Eloquent\Relations\HasMany but Rapyd can handle only BelongsToMany, BelongsTo, and HasOne`. So I added this new case and everything works like a charm now.

**Comment by zofe** [comment]
it's possible to see some code  about your interaction about datagrid and dataform?
why you're patching dataform if your problem is on datagrid ?

**Comment by raylight75** [comment]
In DataGrid:
`$grid = DataGrid::source(Product::with('brands','size'));`
`$grid->add('', 'Front');`
In DataEdit:
`$edit = DataEdit::source(new Product());`
`$edit->add('size.product','Size','tags');`
Everythink displays ok in DataEdit but  when i call method product - belongsTo in Size model i have same error

**Comment by msabev** [comment]
The DataFilter class extends the DataForm class and uses its build method. The build method itself buildes the fields `$this->buildFields();`.

Here is the stack trace of the Exception:
```
in Field.php line 321
at Field->getValue() in Field.php line 567
at Field->build() in Text.php line 13
at Text->build() in DataForm.php line 357
at DataForm->buildFields() in DataForm.php line 500
at DataForm->build() in VmGrid.php line 40
```

**Comment by raylight75** [comment]
Методи добавих твоя код но в dataedit text ми излиза масив
[{"id":9,"product_id":4,"size_id":3},{"id":10,"product_id":4,"size_id":5}], който e правилен просто ме интересува къде се обработват данните преди да се покажат в текст fileld, да мога да обработя масива.

**Comment by zofe** [comment]
@msabev  so the context is to have hasMany  in DataFilter (the exception is not concerned about datagrid).
I'll consider to merge this PR  in near future,  I need to check if there are implications on DataForm where hasMany is not managed  for autoUpdate on saving.

**Comment by zofe** [comment]
I'm sorry, too risky without tests

**Pull request closed without merging**
