### PR TITLE
Translate:  add Simplified Chinese version

### PR DESCRIPTION
**Pull request by icedfish**

### CODE REVIEW

**Comment by zofe** [comment]
hi, it seems that you've committed something that is already merged on master:
https://github.com/zofe/rapyd-laravel/commit/67b4494900114dd08b2c2f1af693d13eb22e505b

you did the sync/fetch with the master before add new commits and then make new PR?
(I mean; git fetch upstream)

**Comment by icedfish** [comment]
It's because I have a PR in my own repo, and I merged it.

but the PR in my own repo is the same with the PR to upstream/master, so it bring no diff files.
the only diff file is in my second commit.

Just ignore the first one ?  or you insist me to redo the change? (maybe I need refork a new repo to erase the old merge commit )

**Comment by zofe** [comment]
no, is just to simplify the work on next PR,  thanks for chinese translation !

**Comment by icedfish** [comment]
Thanks for your rapyd : ) 

I've already introduced it to a lot friends.

BTW, I'm trying to add a new Field Type "Number" now.  It will helps mobile to input number datas because of the html5 number input type.

**Pull request merged**
