### PR TITLE
Changes in Date field to use in DataFilter

### PR DESCRIPTION
**Pull request by farynato**
These are changes to provide automatic conversions in format dates of Date field when it's used in DataFilter to compare the values with DB. The same that it's already implemented for Daterange fields.

### CODE REVIEW

**Comment by zofe** [comment]
I'll test on my env before merge,  can you add give me the link to the related issue?
thanks

**Comment by farynato** [comment]
https://github.com/zofe/rapyd-laravel/issues/165

**Comment by zofe** [comment]
I've tested this patch  but there are problems:  
- if you filter for a range and then you use pagination, range values disappear 
- a "date"  filter should work using "where"  and not a "like", so we must set the clause param.

I'm working on it  (make date field compatible with  datafilter)
so give me some time to resolve this  (I need to refactor a bit  other related stuff).

**Comment by farynato** [comment]
Of course! Thank you!

**Comment by zofe** [comment]
ok, those commits this seems to fix:
https://github.com/zofe/rapyd-laravel/commit/b4ccb4b1151e236cfdde0abf7d9ac21969284843
https://github.com/zofe/rapyd-laravel/commit/2bc4c93b5c3e70b45408ad542aa6d5a4a77943f6

basically there was a problem in pagination too.
 
a bit of words for getValue()  getNewValue():
- the first is used to fill $this->value and the second to fill $this->new_value
- by default $this->value is filled by the value stored in the db (if any)
- by default $this->new_value will be the new value to save/process (from user input)

So,  wen we need to "reformat" user input  we can overwrite getNewValue(),  instead if we need to format db value to show a human readable value we can overwrite getValue().

I reject the commit only because I started from master,  but thanks  and a feedback for current dev-master  will be apreciated.

**Pull request closed without merging**
